### PR TITLE
Refactor prompt template retrieval and update documentation

### LINKED ISSUE #49: update the docs for new prompt template schema and new endpoints
Update the docs for new prompt template schema and all the api changes. Showcase the ways, how new updates will provide a much better UX to end customers.

### PR DESCRIPTION
**Pull request by abubakarsohail**
This pull request refactors the prompt template retrieval code and updates the documentation to reflect the changes. It also fixes a typo in the Get Prompt Template title.

### CODE REVIEW

**Comment by jzone3** [comment]
CleanShot 2024-01-19 at 11 16 34
CleanShot 2024-01-19 at 11 16 13
CleanShot 2024-01-19 at 11 15 20
CleanShot 2024-01-19 at 11 13 49
CleanShot 2024-01-19 at 11 12 38
CleanShot 2024-01-19 at 11 11 57

**Review by jzone3 — CHANGES_REQUESTED** [review]
Please fix images

**Comment by jzone3** [comment]
Good work! We are almost there just a few nits left:

# API REFERENCE

CleanShot 2024-01-29 at 12 01 34

CleanShot 2024-01-29 at 12 02 29


CleanShot 2024-01-29 at 12 02 59


CleanShot 2024-01-29 at 12 04 00


CleanShot 2024-01-29 at 12 04 20


---

CleanShot 2024-01-29 at 12 05 18

CleanShot 2024-01-29 at 12 06 17

CleanShot 2024-01-29 at 12 08 12

**Comment by abubakarsohail** [comment]
@jzone3 

- pushed a fix to remove two options from `prompt_name`. It should only show up as a string now.
- when a field is required, in openapi schema, it's explicitly called out to be required, take `prompt_name` for example. All other fields are considered optional by default. 
- added a description for the rest endpoint `/prompt-templates/{prompt_name}`
- `prefill` was added as part of mapping from our schema to `anthropic`. I'll discuss with @nahuel-borda and remove it.
- added missing description for `llm_kwargs`
- fixed typo in `The prompts.get` and replaced with 'The `prompts.get`'
- `prompts.publish` is not valid for `templates.get` so replaced it with `prompts.get`
- moved the comment to where we are actually grabbing the prompt template

**Review by jzone3 — CHANGES_REQUESTED** [review]
CleanShot 2024-01-30 at 13 53 44

CleanShot 2024-01-30 at 13 56 41

**Review by jzone3 — APPROVED** [review]
LGTM!!!!

**Pull request merged**
