### PR TITLE
58 - Update prompt registry code and REST API endpoint

### PR DESCRIPTION
**Pull request by abubakarsohail**
This pull request updates the prompt registry code and REST API endpoint. It includes changes to the prompt registry code, specifically updating the import statements from `promptlayer.prompts` to `promptlayer.templates`. Additionally, it updates the REST API endpoint from `/rest/prompts` to `/prompt-templates`. These changes ensure that the code is up to date and aligned with the latest conventions and best practices.

### CODE REVIEW

**Comment by Jped** [comment]
@abubakarsohail still see one reference in the docs to `prompts.all()` -- https://promptlayer-58-add-docs-for-returning-all-the-prompt-templa.mintlify.app/features/prompt-registry/overview

Screenshot 2024-03-22 at 12 15 53 PM

**Comment by Jped** [comment]
What is this "prefill" and "system" i dont see it in the description for the API
Screenshot 2024-03-22 at 12 23 47 PM

**Review by Jped — APPROVED** [review]
left two comments -- please address then you should be ready to go.

**Comment by abubakarsohail** [comment]
> https://promptlayer-58-add-docs-for-returning-all-the-prompt-templa.mintlify.app/features/prompt-registry/overview

Fixed.

**Comment by abubakarsohail** [comment]
> @abubakarsohail still see one reference in the docs to `prompts.all()` -- https://promptlayer-58-add-docs-for-returning-all-the-prompt-templa.mintlify.app/features/prompt-registry/overview
> 
> Screenshot 2024-03-22 at 12 15 53 PM

Fixed.

**Pull request merged**
